---
- name: Deploy dotfiles
  hosts: all
  roles:
    - role: ansible
    - role: sudo
    - role: ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: yes
    - role: dotfiles
    - role: zsh
    - role: vim
    - role: awscli
