---
- name: Deploy dotfiles for EC2
  hosts: all
  vars:
    target_user: "ec2-user"
  roles:
    - role: AmazonLinux
      when: ansible_facts['distribution'] == 'Amazon'
      become: yes
    - role: MIRACLELinux
      when: ansible_facts['distribution'] == 'MIRACLE'
      become: yes
    - role: dotfiles
    - role: zsh
    - role: vim