---
- name: Deploy dotfiles for EC2
  hosts: all
  vars:
    target_user: "ssm-user"
  roles:
    - role: AmazonLinux
      when: ansible_facts['distribution'] == 'Amazon'
      become: yes
    - role: MIRACLELinux
      when: ansible_facts['distribution'] == 'MIRACLE'
      become: yes
    - role: ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: yes
    - role: ubuntu-ec2
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: yes
    - role: sudo
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: yes
    - role: dotfiles
      become: yes
    - role: vim
      become: yes