---
- name: Check is aws command installed
  command:
    cmd: "which aws"
  environment:
    PATH: "/usr/loca/bin:{{ ansible_env.PATH }}"
  register: exist_awscli
  changed_when: false
  failed_when: false
- name: Get awscli v2 version
  shell:
    cmd: "aws --version 2>&1 | grep -oP '(?<=aws-cli\\/)\\d+\\.\\d+\\.\\d+'"
  environment:
    PATH: "/usr/loca/bin:{{ ansible_env.PATH }}"
  register: version_awscli
  changed_when: false
  failed_when: false
  when:
    exist_awscli.rc == 0
- block:
  - name: Create Working space for awscli
    file:
      path: "/tmp/awscli"
      state: directory
      mode: "0755"
  - name: Download awscli Zip file
    get_url:
      url: "{{ awscli.src }}"
      dest: "/tmp/{{ awscli.zip }}"
  - name: Unarchive awscli Zip file
    unarchive:
      src: "/tmp/{{ awscli.zip }}"
      dest: "/tmp/awscli"
      copy: no
  - name: Install awscli
    command:
      cmd: "./aws/install --update"
      chdir: "/tmp/awscli"
      creates: yes
    become: yes
  - name: Remove working files for awscli
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - "/tmp/{{ awscli.zip }}"
      - "/tmp/awscli"
  when:
    exist_awscli.rc != 0
    or (version_awscli is defined and version_awscli.stdout.find(cli_version) == -1)
- name: Install aws-mfa module
  pip:
    name: aws-mfa
    state: latest
  become: yes
- name: Put awsotp wrapper
  template:
    src: awsotp.j2
    dest: "/usr/local/bin/awsotp"
    mode: "0755"
  become: yes
- name: Create aws config directory
  file:
    dest: "/home/{{ target_user }}/.aws"
    state: directory
    mode: "0755"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
- name: Put config file
  copy:
    src: aws.config
    dest: "/home/{{ target_user }}/.aws/config"
    mode: "0600"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
- name: Put credential file
  template:
    src: credentials.j2
    dest: "/home/{{ target_user }}/.aws/credentials"
    mode: "0600"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Create Working space for rain
  file:
    path: "/tmp/rain"
    state: directory
    mode: "0755"
  changed_when: false
- block:
  - name: Download rain Zip file
    get_url:
      url: "{{ rain.x86_64src }}"
      dest: "/tmp/{{ rain.x86_64zip }}"
    changed_when: false
  - name: Unarchive rain Zip file
    unarchive:
      src: "/tmp/{{ rain.x86_64zip }}"
      dest: "/tmp/rain"
      copy: no
    changed_when: false
  - name: Copy rain to /usr/local/bin
    copy:
      src: "/tmp/rain/rain-v{{ rain_version }}_linux-amd64/rain"
      dest: "/usr/local/bin/"
      mode: "0755"
    become: yes
  - name: Remove working files for rain
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - "/tmp/{{ rain.x86_64zip }}"
      - "/tmp/rain"
    changed_when: false
  when:
    ansible_architecture == "x86_64"

- name: Install cfn-lint
  pip:
    name: cfn-lint
  become: yes