---
- name: Put Git config file
  copy:
    src: gitconfig
    dest: "/home/{{ target_user }}/.gitconfig"
- name: Put Git ignore file
  copy:
    src: gitignore
    dest: "/home/{{ target_user }}/.gitignore"
- name: Put tmux config file
  copy:
    src: tmux.conf
    dest: "/home/{{ target_user }}/.tmux.conf"
- name: Put zshrc file
  copy:
    src: zshrc
    dest: "/home/{{ target_user }}/.zshrc"
- name: Put vimrc file
  copy:
    src: vimrc
    dest: "/home/{{ target_user }}/.vimrc"
