---
- name: Clone oh-my-zsh
  git:
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ ansible_env.USER }}/.oh-my-zsh"
- name: Set default shell as zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  become: yes
