---
- name: Update packages (Ubuntu)
  apt:
    update_cache: yes
    name: "*"
    state: latest
- name: Install packages (Ubuntu)
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop:
    - tmux
    - vim
    - zsh
    - zip
    - unzip
    - python3-pip
    - oathtool
- name: Install packages for SSM x86_64 (Ubuntu)
  apt:
    deb: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb
  when:
    ansible_architecture == "x86_64"
- name: Install aws-sam-cli
  pip:
    name: aws-sam-cli