---
- name: Update packages (Ubuntu)
  apt:
    update_cache: yes
    name: "*"
    state: latest
- name: Install packages (Ubuntu)
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop:
    - tmux
    - vim
    - zsh
    - unzip
    - python3-pip
