---
- name: Enable epel repository
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    disable_gpg_check: yes
- name: Enable jdoss/wireguard copr repository
  community.general.copr:
    state: enabled
    name: jdoss/wireguard
    chroot: epel-8-x86_64
- name: Install require packages
  dnf:
    name: "{{ item }}"
  loop:
    - wireguard-dkms
    - wireguard-tools
- name: Put config file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0644
- name: Start service of systemd for wireguard
  systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: true