name: Deploy repository ZIP file to AWS S3
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create zip file
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dotfiles-ansible-$env:GITHUB_REF_NAME.zip .
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
      - name: Copy zip file to S3
        run: aws s3 cp dotfiles-ansible-$env:GITHUB_REF_NAME.zip s3://tencho-lab-github-actions-artifact/dotfiles-ansible/